<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Wus2026</RootNamespace>
		<AssemblyName>Wus2026</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministic>true</Deterministic>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="System.ServiceModel.Primitives" Version="4.10.3" />
		<PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.2" />
	</ItemGroup>
</Project>