//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceStatusInformatie
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class foutType
    {
        
        private string foutcodeField;
        
        private string foutbeschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string foutcode
        {
            get
            {
                return this.foutcodeField;
            }
            set
            {
                this.foutcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string foutbeschrijving
        {
            get
            {
                return this.foutbeschrijvingField;
            }
            set
            {
                this.foutbeschrijvingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class identiteitType
    {
        
        private string nummerField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string nummer
        {
            get
            {
                return this.nummerField;
            }
            set
            {
                this.nummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/", ConfigurationName="ServiceReferenceStatusInformatie.StatusinformatieService_V1_2")]
    public interface StatusinformatieService_V1_2
    {
        
        // CODEGEN: Generating message contract since the operation getBerichtsoorten is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice_V1_2/getBerichtsoortenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getBerichtsoortenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReferenceStatusInformatie.foutType), Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getBerichtsoorten/Fault/", Name="statusinformatieFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReferenceStatusInformatie.getBerichtsoortenResponse1 getBerichtsoorten(ServiceReferenceStatusInformatie.getBerichtsoortenRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getProcessen is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice_V1_2/getProcessenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getProcessenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReferenceStatusInformatie.foutType), Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getProcessen/Fault/", Name="statusinformatieFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReferenceStatusInformatie.getProcessenResponse1 getProcessen(ServiceReferenceStatusInformatie.getProcessenRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getStatussenProces is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice_V1_2/getStatussenProcesRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getStatussenProcesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReferenceStatusInformatie.foutType), Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getStatussenProces/Fault/", Name="statusinformatieFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReferenceStatusInformatie.getStatussenProcesResponse1 getStatussenProces(ServiceReferenceStatusInformatie.getStatussenProcesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getNieuweStatussenProces is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice_V1_2/getNieuweStatussenProcesRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussenProcesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReferenceStatusInformatie.foutType), Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussenProces/Fault/", Name="statusinformatieFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReferenceStatusInformatie.getNieuweStatussenProcesResponse1 getNieuweStatussenProces(ServiceReferenceStatusInformatie.getNieuweStatussenProcesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getNieuweStatussen is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice_V1_2/getNieuweStatussenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReferenceStatusInformatie.foutType), Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussen/Fault/", Name="statusinformatieFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReferenceStatusInformatie.getNieuweStatussenResponse1 getNieuweStatussen(ServiceReferenceStatusInformatie.getNieuweStatussenRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getBerichtsoortenRequest
    {
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string autorisatieAdresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public identiteitType identiteitBelanghebbende
        {
            get
            {
                return this.identiteitBelanghebbendeField;
            }
            set
            {
                this.identiteitBelanghebbendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string autorisatieAdres
        {
            get
            {
                return this.autorisatieAdresField;
            }
            set
            {
                this.autorisatieAdresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getBerichtsoortenResponse
    {
        
        private string[] getBerichtsoortenReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("berichtsoort", DataType="normalizedString", IsNullable=false)]
        public string[] getBerichtsoortenReturn
        {
            get
            {
                return this.getBerichtsoortenReturnField;
            }
            set
            {
                this.getBerichtsoortenReturnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBerichtsoortenRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public ServiceReferenceStatusInformatie.getBerichtsoortenRequest getBerichtsoortenRequest;
        
        public getBerichtsoortenRequest1()
        {
        }
        
        public getBerichtsoortenRequest1(ServiceReferenceStatusInformatie.getBerichtsoortenRequest getBerichtsoortenRequest)
        {
            this.getBerichtsoortenRequest = getBerichtsoortenRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBerichtsoortenResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public ServiceReferenceStatusInformatie.getBerichtsoortenResponse getBerichtsoortenResponse;
        
        public getBerichtsoortenResponse1()
        {
        }
        
        public getBerichtsoortenResponse1(ServiceReferenceStatusInformatie.getBerichtsoortenResponse getBerichtsoortenResponse)
        {
            this.getBerichtsoortenResponse = getBerichtsoortenResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getProcessenRequest
    {
        
        private string berichtsoortField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string autorisatieAdresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string berichtsoort
        {
            get
            {
                return this.berichtsoortField;
            }
            set
            {
                this.berichtsoortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public identiteitType identiteitBelanghebbende
        {
            get
            {
                return this.identiteitBelanghebbendeField;
            }
            set
            {
                this.identiteitBelanghebbendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=2)]
        public string autorisatieAdres
        {
            get
            {
                return this.autorisatieAdresField;
            }
            set
            {
                this.autorisatieAdresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getProcessenResponse
    {
        
        private ProcesResultaat[] getProcessenReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ProcesResultaat[] getProcessenReturn
        {
            get
            {
                return this.getProcessenReturnField;
            }
            set
            {
                this.getProcessenReturnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class ProcesResultaat
    {
        
        private string kenmerkField;
        
        private string berichtsoortField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private identiteitType identiteitOntvangerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string kenmerk
        {
            get
            {
                return this.kenmerkField;
            }
            set
            {
                this.kenmerkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string berichtsoort
        {
            get
            {
                return this.berichtsoortField;
            }
            set
            {
                this.berichtsoortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public identiteitType identiteitBelanghebbende
        {
            get
            {
                return this.identiteitBelanghebbendeField;
            }
            set
            {
                this.identiteitBelanghebbendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public identiteitType identiteitOntvanger
        {
            get
            {
                return this.identiteitOntvangerField;
            }
            set
            {
                this.identiteitOntvangerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProcessenRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public ServiceReferenceStatusInformatie.getProcessenRequest getProcessenRequest;
        
        public getProcessenRequest1()
        {
        }
        
        public getProcessenRequest1(ServiceReferenceStatusInformatie.getProcessenRequest getProcessenRequest)
        {
            this.getProcessenRequest = getProcessenRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProcessenResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public ServiceReferenceStatusInformatie.getProcessenResponse getProcessenResponse;
        
        public getProcessenResponse1()
        {
        }
        
        public getProcessenResponse1(ServiceReferenceStatusInformatie.getProcessenResponse getProcessenResponse)
        {
            this.getProcessenResponse = getProcessenResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getStatussenProcesRequest
    {
        
        private string kenmerkField;
        
        private string autorisatieAdresField;
        
        private System.DateTime tijdstempelVanafField;
        
        private bool tijdstempelVanafFieldSpecified;
        
        private System.DateTime tijdstempelTotField;
        
        private bool tijdstempelTotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string kenmerk
        {
            get
            {
                return this.kenmerkField;
            }
            set
            {
                this.kenmerkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string autorisatieAdres
        {
            get
            {
                return this.autorisatieAdresField;
            }
            set
            {
                this.autorisatieAdresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime tijdstempelVanaf
        {
            get
            {
                return this.tijdstempelVanafField;
            }
            set
            {
                this.tijdstempelVanafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelVanafSpecified
        {
            get
            {
                return this.tijdstempelVanafFieldSpecified;
            }
            set
            {
                this.tijdstempelVanafFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelTot
        {
            get
            {
                return this.tijdstempelTotField;
            }
            set
            {
                this.tijdstempelTotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelTotSpecified
        {
            get
            {
                return this.tijdstempelTotFieldSpecified;
            }
            set
            {
                this.tijdstempelTotFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getStatussenProcesResponse
    {
        
        private StatusResultaat[] getStatussenProcesReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StatusResultaat[] getStatussenProcesReturn
        {
            get
            {
                return this.getStatussenProcesReturnField;
            }
            set
            {
                this.getStatussenProcesReturnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class StatusResultaat
    {
        
        private string kenmerkField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string statuscodeField;
        
        private System.DateTime tijdstempelStatusField;
        
        private string statusomschrijvingField;
        
        private foutType statusFoutcodeField;
        
        private string statusdetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string kenmerk
        {
            get
            {
                return this.kenmerkField;
            }
            set
            {
                this.kenmerkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public identiteitType identiteitBelanghebbende
        {
            get
            {
                return this.identiteitBelanghebbendeField;
            }
            set
            {
                this.identiteitBelanghebbendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
        public string statuscode
        {
            get
            {
                return this.statuscodeField;
            }
            set
            {
                this.statuscodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelStatus
        {
            get
            {
                return this.tijdstempelStatusField;
            }
            set
            {
                this.tijdstempelStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=4)]
        public string statusomschrijving
        {
            get
            {
                return this.statusomschrijvingField;
            }
            set
            {
                this.statusomschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public foutType statusFoutcode
        {
            get
            {
                return this.statusFoutcodeField;
            }
            set
            {
                this.statusFoutcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=6)]
        public string statusdetails
        {
            get
            {
                return this.statusdetailsField;
            }
            set
            {
                this.statusdetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStatussenProcesRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public ServiceReferenceStatusInformatie.getStatussenProcesRequest getStatussenProcesRequest;
        
        public getStatussenProcesRequest1()
        {
        }
        
        public getStatussenProcesRequest1(ServiceReferenceStatusInformatie.getStatussenProcesRequest getStatussenProcesRequest)
        {
            this.getStatussenProcesRequest = getStatussenProcesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStatussenProcesResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public ServiceReferenceStatusInformatie.getStatussenProcesResponse getStatussenProcesResponse;
        
        public getStatussenProcesResponse1()
        {
        }
        
        public getStatussenProcesResponse1(ServiceReferenceStatusInformatie.getStatussenProcesResponse getStatussenProcesResponse)
        {
            this.getStatussenProcesResponse = getStatussenProcesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweStatussenProcesRequest
    {
        
        private string kenmerkField;
        
        private string autorisatieAdresField;
        
        private System.DateTime tijdstempelVanafField;
        
        private bool tijdstempelVanafFieldSpecified;
        
        private System.DateTime tijdstempelTotField;
        
        private bool tijdstempelTotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string kenmerk
        {
            get
            {
                return this.kenmerkField;
            }
            set
            {
                this.kenmerkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string autorisatieAdres
        {
            get
            {
                return this.autorisatieAdresField;
            }
            set
            {
                this.autorisatieAdresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime tijdstempelVanaf
        {
            get
            {
                return this.tijdstempelVanafField;
            }
            set
            {
                this.tijdstempelVanafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelVanafSpecified
        {
            get
            {
                return this.tijdstempelVanafFieldSpecified;
            }
            set
            {
                this.tijdstempelVanafFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelTot
        {
            get
            {
                return this.tijdstempelTotField;
            }
            set
            {
                this.tijdstempelTotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelTotSpecified
        {
            get
            {
                return this.tijdstempelTotFieldSpecified;
            }
            set
            {
                this.tijdstempelTotFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweStatussenProcesResponse
    {
        
        private StatusResultaat[] getNieuweStatussenProcesReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StatusResultaat[] getNieuweStatussenProcesReturn
        {
            get
            {
                return this.getNieuweStatussenProcesReturnField;
            }
            set
            {
                this.getNieuweStatussenProcesReturnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweStatussenProcesRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public ServiceReferenceStatusInformatie.getNieuweStatussenProcesRequest getNieuweStatussenProcesRequest;
        
        public getNieuweStatussenProcesRequest1()
        {
        }
        
        public getNieuweStatussenProcesRequest1(ServiceReferenceStatusInformatie.getNieuweStatussenProcesRequest getNieuweStatussenProcesRequest)
        {
            this.getNieuweStatussenProcesRequest = getNieuweStatussenProcesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweStatussenProcesResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public ServiceReferenceStatusInformatie.getNieuweStatussenProcesResponse getNieuweStatussenProcesResponse;
        
        public getNieuweStatussenProcesResponse1()
        {
        }
        
        public getNieuweStatussenProcesResponse1(ServiceReferenceStatusInformatie.getNieuweStatussenProcesResponse getNieuweStatussenProcesResponse)
        {
            this.getNieuweStatussenProcesResponse = getNieuweStatussenProcesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweStatussenRequest
    {
        
        private string berichtsoortField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string autorisatieAdresField;
        
        private System.DateTime tijdstempelVanafField;
        
        private bool tijdstempelVanafFieldSpecified;
        
        private System.DateTime tijdstempelTotField;
        
        private bool tijdstempelTotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string berichtsoort
        {
            get
            {
                return this.berichtsoortField;
            }
            set
            {
                this.berichtsoortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public identiteitType identiteitBelanghebbende
        {
            get
            {
                return this.identiteitBelanghebbendeField;
            }
            set
            {
                this.identiteitBelanghebbendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=2)]
        public string autorisatieAdres
        {
            get
            {
                return this.autorisatieAdresField;
            }
            set
            {
                this.autorisatieAdresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelVanaf
        {
            get
            {
                return this.tijdstempelVanafField;
            }
            set
            {
                this.tijdstempelVanafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelVanafSpecified
        {
            get
            {
                return this.tijdstempelVanafFieldSpecified;
            }
            set
            {
                this.tijdstempelVanafFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime tijdstempelTot
        {
            get
            {
                return this.tijdstempelTotField;
            }
            set
            {
                this.tijdstempelTotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelTotSpecified
        {
            get
            {
                return this.tijdstempelTotFieldSpecified;
            }
            set
            {
                this.tijdstempelTotFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweStatussenResponse
    {
        
        private StatusResultaat[] getNieuweStatussenReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StatusResultaat[] getNieuweStatussenReturn
        {
            get
            {
                return this.getNieuweStatussenReturnField;
            }
            set
            {
                this.getNieuweStatussenReturnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweStatussenRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public ServiceReferenceStatusInformatie.getNieuweStatussenRequest getNieuweStatussenRequest;
        
        public getNieuweStatussenRequest1()
        {
        }
        
        public getNieuweStatussenRequest1(ServiceReferenceStatusInformatie.getNieuweStatussenRequest getNieuweStatussenRequest)
        {
            this.getNieuweStatussenRequest = getNieuweStatussenRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweStatussenResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public ServiceReferenceStatusInformatie.getNieuweStatussenResponse getNieuweStatussenResponse;
        
        public getNieuweStatussenResponse1()
        {
        }
        
        public getNieuweStatussenResponse1(ServiceReferenceStatusInformatie.getNieuweStatussenResponse getNieuweStatussenResponse)
        {
            this.getNieuweStatussenResponse = getNieuweStatussenResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface StatusinformatieService_V1_2Channel : ServiceReferenceStatusInformatie.StatusinformatieService_V1_2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class StatusinformatieService_V1_2Client : System.ServiceModel.ClientBase<ServiceReferenceStatusInformatie.StatusinformatieService_V1_2>, ServiceReferenceStatusInformatie.StatusinformatieService_V1_2
    {
        
        public StatusinformatieService_V1_2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceStatusInformatie.getBerichtsoortenResponse1 ServiceReferenceStatusInformatie.StatusinformatieService_V1_2.getBerichtsoorten(ServiceReferenceStatusInformatie.getBerichtsoortenRequest1 request)
        {
            return base.Channel.getBerichtsoorten(request);
        }
        
        public ServiceReferenceStatusInformatie.getBerichtsoortenResponse getBerichtsoorten(ServiceReferenceStatusInformatie.getBerichtsoortenRequest getBerichtsoortenRequest)
        {
            ServiceReferenceStatusInformatie.getBerichtsoortenRequest1 inValue = new ServiceReferenceStatusInformatie.getBerichtsoortenRequest1();
            inValue.getBerichtsoortenRequest = getBerichtsoortenRequest;
            ServiceReferenceStatusInformatie.getBerichtsoortenResponse1 retVal = ((ServiceReferenceStatusInformatie.StatusinformatieService_V1_2)(this)).getBerichtsoorten(inValue);
            return retVal.getBerichtsoortenResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceStatusInformatie.getProcessenResponse1 ServiceReferenceStatusInformatie.StatusinformatieService_V1_2.getProcessen(ServiceReferenceStatusInformatie.getProcessenRequest1 request)
        {
            return base.Channel.getProcessen(request);
        }
        
        public ServiceReferenceStatusInformatie.getProcessenResponse getProcessen(ServiceReferenceStatusInformatie.getProcessenRequest getProcessenRequest)
        {
            ServiceReferenceStatusInformatie.getProcessenRequest1 inValue = new ServiceReferenceStatusInformatie.getProcessenRequest1();
            inValue.getProcessenRequest = getProcessenRequest;
            ServiceReferenceStatusInformatie.getProcessenResponse1 retVal = ((ServiceReferenceStatusInformatie.StatusinformatieService_V1_2)(this)).getProcessen(inValue);
            return retVal.getProcessenResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceStatusInformatie.getStatussenProcesResponse1 ServiceReferenceStatusInformatie.StatusinformatieService_V1_2.getStatussenProces(ServiceReferenceStatusInformatie.getStatussenProcesRequest1 request)
        {
            return base.Channel.getStatussenProces(request);
        }
        
        public ServiceReferenceStatusInformatie.getStatussenProcesResponse getStatussenProces(ServiceReferenceStatusInformatie.getStatussenProcesRequest getStatussenProcesRequest)
        {
            ServiceReferenceStatusInformatie.getStatussenProcesRequest1 inValue = new ServiceReferenceStatusInformatie.getStatussenProcesRequest1();
            inValue.getStatussenProcesRequest = getStatussenProcesRequest;
            ServiceReferenceStatusInformatie.getStatussenProcesResponse1 retVal = ((ServiceReferenceStatusInformatie.StatusinformatieService_V1_2)(this)).getStatussenProces(inValue);
            return retVal.getStatussenProcesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceStatusInformatie.getNieuweStatussenProcesResponse1 ServiceReferenceStatusInformatie.StatusinformatieService_V1_2.getNieuweStatussenProces(ServiceReferenceStatusInformatie.getNieuweStatussenProcesRequest1 request)
        {
            return base.Channel.getNieuweStatussenProces(request);
        }
        
        public ServiceReferenceStatusInformatie.getNieuweStatussenProcesResponse getNieuweStatussenProces(ServiceReferenceStatusInformatie.getNieuweStatussenProcesRequest getNieuweStatussenProcesRequest)
        {
            ServiceReferenceStatusInformatie.getNieuweStatussenProcesRequest1 inValue = new ServiceReferenceStatusInformatie.getNieuweStatussenProcesRequest1();
            inValue.getNieuweStatussenProcesRequest = getNieuweStatussenProcesRequest;
            ServiceReferenceStatusInformatie.getNieuweStatussenProcesResponse1 retVal = ((ServiceReferenceStatusInformatie.StatusinformatieService_V1_2)(this)).getNieuweStatussenProces(inValue);
            return retVal.getNieuweStatussenProcesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceStatusInformatie.getNieuweStatussenResponse1 ServiceReferenceStatusInformatie.StatusinformatieService_V1_2.getNieuweStatussen(ServiceReferenceStatusInformatie.getNieuweStatussenRequest1 request)
        {
            return base.Channel.getNieuweStatussen(request);
        }
        
        public ServiceReferenceStatusInformatie.getNieuweStatussenResponse getNieuweStatussen(ServiceReferenceStatusInformatie.getNieuweStatussenRequest getNieuweStatussenRequest)
        {
            ServiceReferenceStatusInformatie.getNieuweStatussenRequest1 inValue = new ServiceReferenceStatusInformatie.getNieuweStatussenRequest1();
            inValue.getNieuweStatussenRequest = getNieuweStatussenRequest;
            ServiceReferenceStatusInformatie.getNieuweStatussenResponse1 retVal = ((ServiceReferenceStatusInformatie.StatusinformatieService_V1_2)(this)).getNieuweStatussen(inValue);
            return retVal.getNieuweStatussenResponse;
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
    }
}
