//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceAanleveren
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class foutType
    {
        
        private string foutcodeField;
        
        private string foutbeschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string foutcode
        {
            get
            {
                return this.foutcodeField;
            }
            set
            {
                this.foutcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string foutbeschrijving
        {
            get
            {
                return this.foutbeschrijvingField;
            }
            set
            {
                this.foutbeschrijvingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class berichtInhoudType
    {
        
        private string mimeTypeField;
        
        private string bestandsnaamField;
        
        private byte[] inhoudField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string bestandsnaam
        {
            get
            {
                return this.bestandsnaamField;
            }
            set
            {
                this.bestandsnaamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] inhoud
        {
            get
            {
                return this.inhoudField;
            }
            set
            {
                this.inhoudField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class identiteitType
    {
        
        private string nummerField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string nummer
        {
            get
            {
                return this.nummerField;
            }
            set
            {
                this.nummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://logius.nl/digipoort/wus/2.0/aanleverservice/1.2/", ConfigurationName="ServiceReferenceAanleveren.AanleverService_V1_2")]
    public interface AanleverService_V1_2
    {
        
        // CODEGEN: Generating message contract since the operation aanleveren is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/aanleverservice/1.2/AanleverService_V1_2/aanle" +
            "verenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/aanleverservice/1.2/AanleverService/aanleveren" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReferenceAanleveren.foutType), Action="http://logius.nl/digipoort/wus/2.0/aanleverservice/1.2/AanleverService/aanleveren" +
            "/Fault/", Name="aanleverFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReferenceAanleveren.aanleverenResponse aanleveren(ServiceReferenceAanleveren.aanleverenRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class aanleverRequest
    {
        
        private string kenmerkField;
        
        private string berichtsoortField;
        
        private string aanleverkenmerkField;
        
        private string eerderAanleverkenmerkField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string rolBelanghebbendeField;
        
        private identiteitType identiteitOntvangerField;
        
        private string rolOntvangerField;
        
        private berichtInhoudType berichtInhoudField;
        
        private berichtInhoudType[] berichtBijlagenField;
        
        private string autorisatieAdresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string kenmerk
        {
            get
            {
                return this.kenmerkField;
            }
            set
            {
                this.kenmerkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string berichtsoort
        {
            get
            {
                return this.berichtsoortField;
            }
            set
            {
                this.berichtsoortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
        public string aanleverkenmerk
        {
            get
            {
                return this.aanleverkenmerkField;
            }
            set
            {
                this.aanleverkenmerkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=3)]
        public string eerderAanleverkenmerk
        {
            get
            {
                return this.eerderAanleverkenmerkField;
            }
            set
            {
                this.eerderAanleverkenmerkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public identiteitType identiteitBelanghebbende
        {
            get
            {
                return this.identiteitBelanghebbendeField;
            }
            set
            {
                this.identiteitBelanghebbendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=5)]
        public string rolBelanghebbende
        {
            get
            {
                return this.rolBelanghebbendeField;
            }
            set
            {
                this.rolBelanghebbendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public identiteitType identiteitOntvanger
        {
            get
            {
                return this.identiteitOntvangerField;
            }
            set
            {
                this.identiteitOntvangerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=7)]
        public string rolOntvanger
        {
            get
            {
                return this.rolOntvangerField;
            }
            set
            {
                this.rolOntvangerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public berichtInhoudType berichtInhoud
        {
            get
            {
                return this.berichtInhoudField;
            }
            set
            {
                this.berichtInhoudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("bijlage", IsNullable=false)]
        public berichtInhoudType[] berichtBijlagen
        {
            get
            {
                return this.berichtBijlagenField;
            }
            set
            {
                this.berichtBijlagenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=10)]
        public string autorisatieAdres
        {
            get
            {
                return this.autorisatieAdresField;
            }
            set
            {
                this.autorisatieAdresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class aanleverResponse
    {
        
        private string kenmerkField;
        
        private string berichtsoortField;
        
        private string aanleverkenmerkField;
        
        private string eerderAanleverkenmerkField;
        
        private System.DateTime tijdstempelAangeleverdField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string rolBelanghebbendeField;
        
        private identiteitType identiteitOntvangerField;
        
        private string rolOntvangerField;
        
        private string autorisatieAdresField;
        
        private string statuscodeField;
        
        private System.DateTime tijdstempelStatusField;
        
        private bool tijdstempelStatusFieldSpecified;
        
        private string statusomschrijvingField;
        
        private foutType statusFoutcodeField;
        
        private string statusdetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string kenmerk
        {
            get
            {
                return this.kenmerkField;
            }
            set
            {
                this.kenmerkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string berichtsoort
        {
            get
            {
                return this.berichtsoortField;
            }
            set
            {
                this.berichtsoortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
        public string aanleverkenmerk
        {
            get
            {
                return this.aanleverkenmerkField;
            }
            set
            {
                this.aanleverkenmerkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=3)]
        public string eerderAanleverkenmerk
        {
            get
            {
                return this.eerderAanleverkenmerkField;
            }
            set
            {
                this.eerderAanleverkenmerkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime tijdstempelAangeleverd
        {
            get
            {
                return this.tijdstempelAangeleverdField;
            }
            set
            {
                this.tijdstempelAangeleverdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public identiteitType identiteitBelanghebbende
        {
            get
            {
                return this.identiteitBelanghebbendeField;
            }
            set
            {
                this.identiteitBelanghebbendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=6)]
        public string rolBelanghebbende
        {
            get
            {
                return this.rolBelanghebbendeField;
            }
            set
            {
                this.rolBelanghebbendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public identiteitType identiteitOntvanger
        {
            get
            {
                return this.identiteitOntvangerField;
            }
            set
            {
                this.identiteitOntvangerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=8)]
        public string rolOntvanger
        {
            get
            {
                return this.rolOntvangerField;
            }
            set
            {
                this.rolOntvangerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=9)]
        public string autorisatieAdres
        {
            get
            {
                return this.autorisatieAdresField;
            }
            set
            {
                this.autorisatieAdresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=10)]
        public string statuscode
        {
            get
            {
                return this.statuscodeField;
            }
            set
            {
                this.statuscodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime tijdstempelStatus
        {
            get
            {
                return this.tijdstempelStatusField;
            }
            set
            {
                this.tijdstempelStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelStatusSpecified
        {
            get
            {
                return this.tijdstempelStatusFieldSpecified;
            }
            set
            {
                this.tijdstempelStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=12)]
        public string statusomschrijving
        {
            get
            {
                return this.statusomschrijvingField;
            }
            set
            {
                this.statusomschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public foutType statusFoutcode
        {
            get
            {
                return this.statusFoutcodeField;
            }
            set
            {
                this.statusFoutcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=14)]
        public string statusdetails
        {
            get
            {
                return this.statusdetailsField;
            }
            set
            {
                this.statusdetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aanleverenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public ServiceReferenceAanleveren.aanleverRequest aanleverRequest;
        
        public aanleverenRequest()
        {
        }
        
        public aanleverenRequest(ServiceReferenceAanleveren.aanleverRequest aanleverRequest)
        {
            this.aanleverRequest = aanleverRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aanleverenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public ServiceReferenceAanleveren.aanleverResponse aanleverResponse;
        
        public aanleverenResponse()
        {
        }
        
        public aanleverenResponse(ServiceReferenceAanleveren.aanleverResponse aanleverResponse)
        {
            this.aanleverResponse = aanleverResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface AanleverService_V1_2Channel : ServiceReferenceAanleveren.AanleverService_V1_2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AanleverService_V1_2Client : System.ServiceModel.ClientBase<ServiceReferenceAanleveren.AanleverService_V1_2>, ServiceReferenceAanleveren.AanleverService_V1_2
    {
        
        public AanleverService_V1_2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceAanleveren.aanleverenResponse ServiceReferenceAanleveren.AanleverService_V1_2.aanleveren(ServiceReferenceAanleveren.aanleverenRequest request)
        {
            return base.Channel.aanleveren(request);
        }
        
        public ServiceReferenceAanleveren.aanleverResponse aanleveren(ServiceReferenceAanleveren.aanleverRequest aanleverRequest)
        {
            ServiceReferenceAanleveren.aanleverenRequest inValue = new ServiceReferenceAanleveren.aanleverenRequest();
            inValue.aanleverRequest = aanleverRequest;
            ServiceReferenceAanleveren.aanleverenResponse retVal = ((ServiceReferenceAanleveren.AanleverService_V1_2)(this)).aanleveren(inValue);
            return retVal.aanleverResponse;
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
    }
}
